In [328]:
import numpy as np
import pickle as pkl
import matplotlib.pyplot as plt
import glob
import pandas as pd
import os
import matplotlib as mpl
from numpy import concatenate as cat
from collections import defaultdict
from sklearn import metrics
mpl.rcParams['figure.dpi'] = 250
pd.set_option('precision', 3)
DATASET = 'tbi'

if DATASET == 'tbi':
    seeds = range(7)
elif DATASET == 'csi' or DATASET == 'csi_gbp':
    seeds = range(7)
elif DATASET == 'iai':
    seeds = list(range(7))
    seeds.remove(3)

if DATASET == 'sim':
    seeds = range(10)
    sens_levels = []
    metrics_ = ['auc', 'aps', 'acc', 'f1']
else:
    sens_levels = [0.92, 0.94, 0.96, 0.98]
    metrics_ = ['high_spec_avg', 'spec_0.92', 'spec_0.94', 'spec_0.96', 'spec_0.98', 'auc', 'aps', 'acc']

In [329]:
def plott(model_name, sens, spec, ppv, ax):
    if 'pecarn' in model_name.lower():
        ax.plot(sens[0], spec[0], '.-', label=model_name)
    else:
        ax.plot(sens, spec, '.-', label=model_name)

In [330]:
def multiplot(paths, ax, suffix=""):
    for model_file in paths:
        basename = os.path.basename(model_file).split('.')[0]
        dct = pkl.load(open(model_file, 'rb'))
        plott(basename, dct['sens_tune'], dct['spec_tune'], dct['ppv_tune'], ax)
    ax.legend(frameon=False, loc='best')
    ax.set_xlim(0.5, 1.05)
    # ax.set_ylim(0, 0.2)

In [331]:
def multiseedplot(group='all'):
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    for k, i in enumerate(seeds[:6]):
        paths = sorted(glob.glob(f'results/{DATASET}/seed_{i}/{group}/*.pkl'))
        multiplot(paths, axes[k // 3, k % 3], group)
    plt.xlabel('sens')
    plt.ylabel('spec')
    plt.tight_layout()

In [332]:
# multiseedplot()

In [333]:
# multiseedplot(group='young')

In [334]:
# multiseedplot(group='old')

In [337]:
def pkl_to_table(group):
    table = defaultdict(lambda:[])
    for i in seeds:
        seed_paths = sorted(glob.glob(f'results/{DATASET}/seed_{i}/{group}/*.pkl'))
        table_index = [os.path.basename(f).split('.')[0] for f in seed_paths]
        for model_file in seed_paths:
            dct = pkl.load(open(model_file, 'rb'))
            specs = np.array(dct['spec_tune'])
            senses = np.array(dct['sens_tune'])
            precisions = np.array(dct['ppv_tune'])
            for sens in sens_levels:
                table[f'spec_{sens}_seed_{i}'].append(
                    np.max(specs[senses > sens]) if specs[senses > sens].shape[0] > 0 else 0.0)
            table[f'auc_seed_{i}'].append(metrics.auc(1 - specs, senses))
            # table[f'auprc_seed_{i}'].append(metrics.auc(senses, np.nan_to_num(precisions, nan=1)))
            table[f'aps_seed_{i}'].append(-np.sum(np.diff(senses) * np.array(precisions)[:-1]))
            table[f'acc_seed_{i}'].append(dct['acc'])
            # table[f'f1_seed_{i}'].append(dct['f1'])
        
    res_table = pd.DataFrame(table, index=table_index)
    if sens_levels:
        for i in seeds:
            res_table[f'high_spec_avg_seed_{i}'] = res_table.loc[
                :, [f'spec_0.92_seed_{i}', f'spec_0.94_seed_{i}', f'spec_0.96_seed_{i}', f'spec_0.98_seed_{i}']].mean(axis=1)

    for metric in metrics_:
        res_table_metric = res_table.loc[:, res_table.columns.str.contains(metric)]
        res_table[metric] = res_table_metric.mean(axis=1)

    # res_table['high_spec_avg'] = res_table[
    #     [f'spec_0.94', f'spec_0.96', f'spec_0.98']].mean(axis=1)

    for metric in metrics_:
        res_table_metric = res_table.loc[:, res_table.columns.str.contains(metric)]
        res_table[f'{metric}_std_err'] = res_table_metric.std(axis=1) / np.sqrt(10)
        # res_table[f'{metric}_std'] = res_table_metric.std(axis=1)
        
    return res_table

In [338]:
pkl_to_table('all').to_csv(f'results/{DATASET}/all_average.csv')
pkl_to_table('young').to_csv(f'results/{DATASET}/young_average.csv')
pkl_to_table('old').to_csv(f'results/{DATASET}/old_average.csv')

In [346]:
pkl_to_table('all').iloc[[0, 3, 7, 6], -16:].style.highlight_max(color='blue')

In [347]:
pkl_to_table('young').iloc[[0, 1, 2, 3, 7, 8, 6], -16:].style.highlight_max(color='blue')

In [348]:
pkl_to_table('old').iloc[[0, 1, 2, 3, 7, 8, 6], -16:].style.highlight_max(color='blue')